# This file is a template, and might need editing before it works on your project.
# Official docker image.
before_script:
- docker info

build:
  stage: build
  tags:
    - shell-runner
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.ii.org.nz
  - docker build -t docker.ii.org.nz/ii/taiga-docker:taiga-front taiga-front-dist/
  - docker build -t docker.ii.org.nz/ii/taiga-docker:taiga-back taiga-back/
  - docker push docker.ii.org.nz/ii/taiga-docker:taiga-front
  - docker push docker.ii.org.nz/ii/taiga-docker:taiga-back